media_folder: 'images'
public_folder: '/images'

publish_mode: editorial_workflow

backend:
 name: github
 repo: bdadam/netlifycms-test 

collections:
 - name: article
   label: Articles
   folder: articles
   create: true
   fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }