media_folder: 'images'
public_folder: '/images'

publish_mode: editorial_workflow

# backend:
#   name: git-gateway
#   branch: master

backend:
 name: github
 repo: bdadam/netlifycms-test 

collections:
 - name: article
   label: Article
   folder: articles
   create: true
   slug: {{ slug }}
   fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }